version: '3.4'

services:
  sample.api:
    image: ${DOCKER_REGISTRY-}sampleapi
    ports:
       - 8000:80
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
            - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      #//TODO: NEVER CHECK IN PASSWORD TO REPOSITORY - THIS IS ONLY A SAMPLE
      SA_PASSWORD: "yourpassword"
      ACCEPT_EULA: "Y"
      ASPNETCORE_ENVIRONMENT: "development"
